CREATE TABLE `people` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`voter_id` INT(12) DEFAULT NULL,
	`county_code` INT(12) DEFAULT NULL,
	`county` VARCHAR(64) DEFAULT NULL,
	`last_name` VARCHAR(256) DEFAULT NULL,
	`first_name` VARCHAR(256) DEFAULT NULL, 
	`middle_name` VARCHAR(256) DEFAULT NULL, 
	`name_suffix` VARCHAR(50) DEFAULT NULL, 
	`voter_name` VARCHAR(256) DEFAULT NULL, 
	`status_code` VARCHAR(2)  DEFAULT NULL,
	`precinct_name` VARCHAR(20) DEFAULT NULL,
	`address_library_id` VARCHAR(20) DEFAULT NULL,
	`house_num`  VARCHAR(40) DEFAULT NULL,
	`house_suffix` VARCHAR(40) DEFAULT NULL,
	`pre_dir` VARCHAR(40) DEFAULT NULL,
	`street_name` VARCHAR(256) DEFAULT NULL,
	`street_type` VARCHAR(256) DEFAULT NULL,
	`post_dir` VARCHAR(40) DEFAULT NULL,
	`unit_type` VARCHAR(40) DEFAULT NULL,
	`unit_num` VARCHAR(40) DEFAULT NULL,
	`address_non_std` VARCHAR(40) DEFAULT NULL,
	`residential_address` VARCHAR(256) DEFAULT NULL,
	`residential_city` VARCHAR(256) DEFAULT NULL,
	`residential_state` VARCHAR(10) DEFAULT NULL,
	`residential_zip_code` VARCHAR(10) DEFAULT NULL,
	`residential_zip_plus` VARCHAR(10)DEFAULT NULL,
	`effective_date` DATETIME DEFAULT NULL,
	`registration_date` DATETIME DEFAULT NULL,
	`status` VARCHAR(10) DEFAULT NULL,
	`status_reason` VARCHAR(60) DEFAULT NULL,
	`birth_year` INT(4) DEFAULT NULL,
	`gender` VARCHAR(10) DEFAULT NULL,
	`precinct` VARCHAR(60) DEFAULT NULL,
	`split`  VARCHAR(60) DEFAULT NULL,
	`voter_status_id` INT(10) DEFAULT NULL,
	`party` VARCHAR(10) DEFAULT NULL,
	`party_affiliation_date` DATETIME DEFAULT NULL,
	`phone_num` VARCHAR(15) DEFAULT NULL,
	`mail_addr1` VARCHAR(255) DEFAULT NULL,
	`mail_addr2` VARCHAR(255) DEFAULT NULL,
	`mail_addr3` VARCHAR(255) DEFAULT NULL,
	`mailing_city` VARCHAR(255) DEFAULT NULL,
	`mailing_state` VARCHAR(10) DEFAULT NULL,
	`mailing_zip_code` VARCHAR(8) DEFAULT NULL,
	`mailing_zip_plus` VARCHAR(5) DEFAULT NULL,
	`mailing_country` VARCHAR(200) DEFAULT NULL,
	`spl_id`  VARCHAR(10) DEFAULT NULL,
	`permanent_mail_in_voter` VARCHAR(200) DEFAULT NULL,
	`congressional` VARCHAR(200) DEFAULT NULL,
	`state_senate` VARCHAR(200) DEFAULT NULL,
	`state_house`VARCHAR(200) DEFAULT NULL, 
	`id_required`VARCHAR(200) DEFAULT NULL,
	PRIMARY KEY ( id )
);

INSERT INTO `voters`.`people`
        (`voter_id`, `county_code`, `county`, `last_name`, `first_name`, `middle_name`, `name_suffix`,
        `voter_name`, `status_code`, `precinct_name`, `address_library_id`, `house_num`, `house_suffix`,
        `pre_dir`, `street_name`, `street_type`, `post_dir`, `unit_type`, `unit_num`, `adds_non_std`
        `residential_address`, `residential_city`, `residential_state`, `residential_zip_code`,
        `residential_zip_plus`, `effective_date`, `registration_date`, `status`, `status_reason`,
        `birth_year`, `gender`, `precinct`, `split`, `voter_status_id`, `party`, `party_affiliation_date`,
        `phone_num`, `mail_addr1`, `mail_addr2`, `mail_addr3`, `mailing_city`, `mailing_state`,
        `mailing_zip_code`, `mailing_zip_plus`, `mailing_country`, `spl_id`, `permanent_mail_in_voter`,
        `congressional`, `state_senate`, `state_house`, `id_required`)
        VALUES ("544769", "47", "Park", "IVERSON", "JOANN",
        "ELAINE", "", "IVERSON, JOANN ELAINE", "A", "2026047010",
        "4952", "44", "", "", "BANDIT",
        "LN", "", "", "", "",
        "44BANDIT LN", "BAILEY", "CO", "80421",
        "1344", "1988-10-14 00:00:00", "1988-10-14 00:00:00", "Active", "",
        "1931", "Female", "2026047010", "010.084", "1", "DEM",
        "1988-10-14 00:00:00", "3038386778", "44 BANDIT LN", "", "",
        "BAILEY", "CO", "80421", "1344", "UNITED STATES OF AMERICA",
        "684", "No", "Congressional 2", "State Senate 2", "State House 60", 
        "N");
